#!/usr/bin/env python3
"""
Script to clean AI attribution from commit messages using git-filter-repo
"""

import re
import sys

# AI-related keywords to filter (case-insensitive)
AI_KEYWORDS = [
    "claude",
    "openai",
    "anthropic",
    "sonnet",
    "opus",
    "gpt-4",
    "gpt-3",
    "chatgpt",
    "copilot",
    "gemini",
    "llama",
]


def clean_commit_message(msg_bytes):
    """Clean AI attribution from a commit message"""
    msg = msg_bytes.decode("utf-8", errors="replace")
    lines = msg.split("\n")
    cleaned_lines = []

    for line in lines:
        line_lower = line.lower()

        # Skip lines with Co-Authored-By patterns
        if "co-authored-by:" in line_lower:
            continue

        # Skip lines with Generated patterns
        if "generated with" in line_lower or "generated by" in line_lower:
            continue

        # Skip lines containing AI keywords
        if any(keyword in line_lower for keyword in AI_KEYWORDS):
            continue

        # Skip lines with AI-related emojis
        if "🤖" in line:
            continue

        # Skip lines with noreply@
        if "noreply@" in line_lower:
            continue

        cleaned_lines.append(line)

    # Remove trailing empty lines
    while cleaned_lines and not cleaned_lines[-1].strip():
        cleaned_lines.pop()

    result = "\n".join(cleaned_lines)

    # If the message is empty or just whitespace after cleaning, use a placeholder
    if not result.strip():
        result = "chore: update"

    return result.encode("utf-8")


# This is called by git-filter-repo
if __name__ == "__main__":
    # For testing
    test_msg = b"""fix(datastore): fix ColumnExpr.values property

- Handle case where _execute() returns numpy array directly
- Add get_series() helper to test_utils

\xf0\x9f\xa4\x96 Generated with [Claude Code](https://claude.com/claude-code)

Co-Authored-By: Claude Opus 4.5 <noreply@anthropic.com>
"""
    print("Before:")
    print(test_msg.decode())
    print("\nAfter:")
    print(clean_commit_message(test_msg).decode())


