"""
Callback module for git-filter-repo to clean AI attribution from commit messages.
Usage: git filter-repo --message-callback 'exec(open("filter_callback.py").read()); return clean_message(message)'
"""

import re

AI_KEYWORDS = [
    b"claude",
    b"openai", 
    b"anthropic",
    b"sonnet",
    b"opus",
    b"gpt-4",
    b"gpt-3",
    b"chatgpt",
    b"copilot",
    b"gemini",
    b"llama",
]


def clean_message(msg_bytes):
    """Clean AI attribution from a commit message (bytes)"""
    lines = msg_bytes.split(b"\n")
    cleaned_lines = []

    for line in lines:
        line_lower = line.lower()

        # Skip lines with Co-Authored-By patterns
        if b"co-authored-by:" in line_lower:
            continue

        # Skip lines with Generated patterns
        if b"generated with" in line_lower or b"generated by" in line_lower:
            continue

        # Skip lines containing AI keywords
        if any(keyword in line_lower for keyword in AI_KEYWORDS):
            continue

        # Skip lines with AI-related emojis (🤖 in UTF-8)
        if b"\xf0\x9f\xa4\x96" in line:
            continue

        # Skip lines with noreply@
        if b"noreply@" in line_lower:
            continue

        cleaned_lines.append(line)

    # Remove trailing empty lines
    while cleaned_lines and not cleaned_lines[-1].strip():
        cleaned_lines.pop()

    result = b"\n".join(cleaned_lines)

    # Ensure message ends with newline
    if result and not result.endswith(b"\n"):
        result += b"\n"

    # If the message is empty after cleaning, use a placeholder
    if not result.strip():
        result = b"chore: update\n"

    return result


